### ISSUE TITLE
load command prints things for minutes and do nothing

### ISSUE THREAD

**Issue by fdev31** [johannesnoordanus/grblhud#2]
Using this software isn't straightforward.

There is no way to run a gcode directly from the command line.
It seems that the "load" command is to be used first, and then run. But load takes an infinite amount of time to run (use case: raspberry pi).
After waiting around 5 minutes watching number scrolling, the `run` command throwed an error.

I tried to type `run <exact same filename>` as I used for load (by the way, lack of completion is annoying) and I see numbers again with no action.

I think the user experience could be improved.
I'm giving up for today but I think most users wouldn't pass the installation step.

Also there is no obvious way to quit.
I tried different (undocumented) classical commands: not working.
^D seems to do something but loops refreshing the command line instead of leaving
^C have to be pressed multiple times...

**Comment by johannesnoordanus** [comment]
For gcodes, just type it (and type enter)
Yes, you need to 'load' the file first, and 'run' it second.
On the prompt '>' type 'help'<enter>, that shows all commands you have.
It is a direct terminal to enter gcode commands (at the prompt)

**Comment by fdev31** [comment]
I can't get it to work, it either makes some integer error or it tells me the file loaded is the one I loaded but apparently it's an error... do you have exact steps to be able to load & send some gcode ?

**Comment by johannesnoordanus** [comment]
Ok, steps:
shell:
> grblhud
[…] grblhud> load filename
[…] grblhud> run filename          (note that path is stripped, I am sorry about that)

It is important to use the file name not its path (on load a path is allowed). This is confusing, I will correct that.
Also buffering isn’t strictly necessary (and confusing as you indicated) so I will correct that, but I have to look at the code a bit to be sure.

Maybe start with a small gcode file!  Not one with a million lines (or so).
I guess the ‘raspberry pi’ has not much memory 1GB?
This means it will run out of memory while buffering.

I will make a direct run (from file) possible. I will also add a non interactive mode, that you (and me and others) can stream files directly to the device.

**Comment by johannesnoordanus** [comment]
Using this software isn't straightforward.

Ok, I will make adaptations, so it will be easy to use. I am also interested to get it to run on a raspberry pi!
> 
> There is no way to run a gcode directly from the command line. It seems that the "load" command is to be used first, and then run. But load takes an infinite amount of time to run (use case: raspberry pi). After waiting around 5 minutes watching number scrolling, the `run` command throwed an error.
I think all memory was taken by the load buffer. See below.
> 
> I tried to type `run <exact same filename>` as I used for load (by the way, lack of completion is annoying) and I see numbers again with no action.
Completion is not included yet, but you do have command history (arrow up and down)!
> 
> I think the user experience could be improved. I'm giving up for today but I think most users wouldn't pass the installation step.

I am sorry about that, I’ll make improvements (as I mentioned above).

> 
> Also there is no obvious way to quit. I tried different (undocumented) classical commands: not working. ^D seems to do something but loops refreshing the command line instead of leaving ^C have to be pressed multiple times...

This is due to the fact that I made ‘load’ non interactive. So, while this command takes time it isn’t run as a separate process and so the grblhud command line parsing loop isn’t running during the load. On the computers I use, this was never a problem, loading is almost instantaneous even for large files.
I will correct this, because this is clearly a problem on slower computers and or extra large gcode files.
Another problem is that a python command line program has limitations what keys it can intercept. For what I understand, ^C and ^D are notorious and intercepted by the python interpreter runtime, so the program does not see them. At least that is what I found, maybe there are ways around that (starting python with special options is no option, because that generates a user dependency …).
I introduced grblhud commands for exit, namely ‘exit’. Typing help at the grblhud prompt ([…] grblhud> help) shows all commands in interactive mode (which is the only mode currently)
I tried to be as explanative as possible, but I will add this help command right after starting in interactive mode. This help also summarizes the grbl commands available.

**Comment by fdev31** [comment]
Really nice to hear :)
But I don't think 1GB will be a limit for gcode, even really big ones.
What is the overhead added to it ? Even loading everything in RAM & not streaming should really be okay. I can't recall how much I have on this one and can't reach it now.
About background loading that's an option but also a complication which might not be needed (I don't really see the point, you will have to wait anyway and it's not that long). Note that having an output makes it much slower in general.

**Comment by johannesnoordanus** [comment]
Did a big update 1.4.0:

Important update:
 - improved usability (load, run, list and stream commands can be aborted now)
 - added commands: OS , stream (stream directly to machine), showgcode (show image),listgcode
 - improved stability
 - added documentation and explanation
 - lowered python version requirement to 3.7

This solves the issues you mention.

**Comment by johannesnoordanus** [comment]
> Really nice to hear :)
> But I don't think 1GB will be a limit for gcode, even really big ones.
> What is the overhead added to it ? Even loading everything in RAM & not streaming should really be okay. I can't recall how much I have on this one and can't reach it now.
> About background loading that's an option but also a complication which might not be needed (I don't really see the point, you will have to wait anyway and it's not that long). Note that having an output makes it much slower in general.

I agree. Update 1.4.0 takes care of it all. (Note that python has no problems at all handling ```<Ctrl><C>```, it can be 'catched' as a 'KeyboardInterrupt'. Added a handler for it. I already handled ```<Ctrl><D>``` inputs.)

I hope this works for you.

**Comment by fdev31** [comment]
Nice, I'll have a look!
Note that there are a few more oddities, like being prompted to select from a list of... once devices, if `/dev/ttyUSB0` haven't been detected.

Also why asking for the bounding box coordinates while it can be inferred from the gcode file ?

There are "weird" commands, using mixed case, as if it was a programming naming standard. Also not typing a known command (eg: bbox vs Bbox) will just not print anything.

Loading a file requires the machine to be idle, while it's not interacting with it as far as I understand.

Bbox is quite interesting, since it requires a special format, which seems to be the one displayed in the CLI, but apparently they are not compatible (copy & paste == KO) and it's not so easy to figure why from the error message:
```
[...]
File loaded 21610 lines, Bbox: (X0,Y-0.000010):(X63.499996,Y110.170000)

0|[Idle XYZ:00.000,00.000,00.000 FS:0,0] grbl> Bbox (X0,Y-0.000010):(X63.499996,Y110.170000)
Error in Bbox argument, format is: (X<min>,Y<min>):(X<max>,Y<max>)
command aborted
```

I figured it's because of the negative Y value.

Also bbox claims it fires the laser and even recommend glasses, but the power in use ("1" as far as I understand) is not enough for most machines. My machine (using a 10W laser) uses 3% (not 3/1000) and even with this value it sometimes not firing up because it's too low.

**Comment by johannesnoordanus** [comment]
> Nice, I'll have a look! Note that there are a few more oddities, like being prompted to select from a list of... once devices, if `/dev/ttyUSB0` haven't been detected.

This is because other devices might be available, but are not apparently. That is a corner case and I update the message accordingly.

> 
> Also why asking for the bounding box coordinates while it can be inferred from the gcode file ?

No, Bbox ```<enter>``` will search in the currently loaded file, the Bbox arguments are used if you want to set a custom bbox.

> 
> There are "weird" commands, using mixed case, as if it was a programming naming standard. Also not typing a known command (eg: bbox vs Bbox) will just not print anything.

Currently not everything is polished. I might add things in that direction for a future release.

> 
> Loading a file requires the machine to be idle, while it's not interacting with it as far as I understand.

True, that restriction is too strict. I'll update that in a future release.

> 
> Bbox is quite interesting, since it requires a special format, which seems to be the one displayed in the CLI, but apparently they are not compatible (copy & paste == KO) and it's not so easy to figure why from the error message:
> 
> ```
> [...]
> File loaded 21610 lines, Bbox: (X0,Y-0.000010):(X63.499996,Y110.170000)
> 
> 0|[Idle XYZ:00.000,00.000,00.000 FS:0,0] grbl> Bbox (X0,Y-0.000010):(X63.499996,Y110.170000)
> Error in Bbox argument, format is: (X<min>,Y<min>):(X<max>,Y<max>)
> command aborted
> ```
> 
> I figured it's because of the negative Y value.

I think that is a bug, negative values should be possible, format should be the same. I'll fix that.

> 
> Also bbox claims it fires the laser and even recommend glasses, but the power in use ("1" as far as I understand) is not enough for most machines. My machine (using a 10W laser) uses 3% (not 3/1000) and even with this value it sometimes not firing up because it's too low.

Ok, I'll let the command look at the machine settings and pick a proper value. (My laser machine has 10W and a setting range [0-1000] and fires up with setting 1. Quite intensely by the way, hence the glasses, also lasers are dangerous when on, even at minimum!)

**Comment by johannesnoordanus** [comment]
> Also bbox claims it fires the laser and even recommend glasses, but the power in use ("1" as far as I understand) is not enough for most machines. My machine (using a 10W laser) uses 3% (not 3/1000) and even with this value it sometimes not firing up because it's too low.

But it is a led laser?

**Comment by johannesnoordanus** [comment]
Updated grblhud to version 1.5.2.
This addresses all issues you mention (note that some issues were already fixed, like the Bbox negative coordinate values and format problems, you mentioned).
The original issue (endless loading, running) is also fixed.
I would like to close this issue.

**Comment by fdev31** [comment]
> > Also bbox claims it fires the laser and even recommend glasses, but the power in use ("1" as far as I understand) is not enough for most machines. My machine (using a 10W laser) uses 3% (not 3/1000) and even with this value it sometimes not firing up because it's too low.
> 
> But it is a led laser?

yes it's a led laser, "longer ray5 10W" if you want to check some details.

**Comment by fdev31** [comment]
I was able to verify this one

**Comment by johannesnoordanus** [comment]
Ok, it is grblhud 1.6.0 (and higher) that has the (rest of the) updates (not 1.5.2).
