### ISSUE TITLE
In WSL2 - Enter does not work, need Ctrl-Enter

### ISSUE THREAD

**Issue by Eloque** [johannesnoordanus/grblhud#3]
When using grblhud in interactive mode, hitting "Enter" on either numpad or regular does not send the command.
For example, typing "help" and "enter" does not execute a command, but instead issues a space.

Using "ctrl-enter" does work, both the regular and numpad enter. 

Using WSL2, Ubuntu 22.04.3 LTS on Windows 10 Pro and Python 3.12.1

**Comment by johannesnoordanus** [comment]
Hi, I just saw your comment.

It could be due to a keyboard mapping problem. Or even the specific keyboard type (hardware) you use.
I read that it is best to configure from the 'windows' side of things.

But, it might be good old 'CRLF' (\r\n) of windows versus 'LF' ('\n') of Unix and Mac.
Both are used to encode the \<enter\> key.
I tested this on Unix and Mac, but that is the '\n' situation. I would expect '\r' '\n' to be two bytes after each other, so the '\n' would always trigger \<enter\> but apparently this is not the case (in your case).

You could adapt line 190 of <i>"install dir of"/grblhud/lineinput.py</i> to:
<code>
if c == '\n' or c == '\r':
</code>
To find out the <i>"install dir of"</i> you can enter:
<code>
    pip show grblhud
</code>

Let me know if that worked, because then I can update the program (I don't use windows systems, so I cannot test this).

Another possibility is to use another virtual machine to run Unix on. This might not have the <enter> issue. It might also be possible to configure the keyboard mapping of the virtual system (WSL2 or other).

Regards,
Johannes

**Comment by Eloque** [comment]
I tried it, but it did not work alas. 

This is an Ubuntu install on WSL2, so it might not be that windows thing with the CRLF.

**Comment by johannesnoordanus** [comment]
Ok, I am a bit surprised. Keyboard remap isn’t an option?
I can give you a patch so you can see what character number it is when you press \<enter\>?

If you add the following line to <i>"install dir of"/grblhud/unblockedgetch.py"</i> (line 73, just before the return statement),
<code>print(f"bytes: '\\\\x{c.hex().upper()}'", end = "")</code>
(edit: updated this line!)
you get the hex code(s) of each key you enter. (You can find the install dir as mentioned in my first reply.)

I am very curious what you get when you run <i>grblhud</i> and push \<enter\>

Regards,
Johannes

P.S. you can also run a direct test on this module by entering:
<code> python "install dir of"/grblhud/unblockedgetch.py </code>
(type anykey - including \<enter\> - to get the hex code(s) for that key, end with 'z')

P.S.2 I did a test using python 3.12 on linux/arm (Manjaro) and it didn't work fine. See my comment below ...

**Comment by johannesnoordanus** [comment]
I'll make a fix for this problem. Point is that python 3.12.1 has a bug, it returns a 0x0D (CR) code instead a 0x0A (LF) code.
I'll also make a bug report for the python community (foundation).
The fix will handle CR and LF equally and is almost the same as the first patch I supplied:

You can add a class variable at line 33 and change line 191 of "install dir of"/grblhud/lineinput.py to:

    LF                  = '\x0A'        # or '\n'


    if c == Input.LF or c == Input.CR:
        print(Input.LF, end = '', flush=True) 

This will do the trick.

**Comment by johannesnoordanus** [comment]
Created a python bug report for this issue: https://github.com/python/cpython/issues/114328
```
pip install -U grblhud
```
This installs version 1.7.8 of grblhud and fixes the \<enter\> issue.

**Comment by johannesnoordanus** [comment]
Issue is fixed. Python bug will be fixed in a next release: https://github.com/python/cpython/issues/114328
